/// List of hospitals in Bangladesh organized alphabetically for dropdown selection
class HospitalConstants {
  static const List<String> bangladeshHospitals = [
    'Ad-din Akij Medical College Hospital, Khulna',
    'Ad-din Sakina Medical College Hospital, Jessore',
    'Ad-din Women\'s Medical College Hospital, Dhaka',
    'Aichi Hospital, Dhaka',
    'Al Haramain Hospital, Sylhet',
    'Ambia Memorial Hospital, Barisal',
    'AMZ Hospital Ltd. Dhaka',
    'Anwer Khan Modern Hospital Ltd, Dhaka',
    'Anwer Khan Modern Medical College Dhanmondi, Dhaka',
    'Arif Memorial Hospital, Barishal',
    'Ayesha Haque Hospital, Beanibazar, Sylhet',
    'Aysha Memorial Specialised Hospital, Dhaka',
    'Bangladesh Assisted Conception Center, Women\'s & Children Hospital Pvt Limited (BACC) Dhaka',
    'Bangladesh Eye Hospital Limited, Dhaka',
    'Bangladesh Institute of Research and Rehabilitation for Diabetes, Endocrine and Metabolic Disorders (BIRDEM)',
    'Bangladesh Medical College Hospital, Dhaka',
    'Bangladesh Medical University',
    'Bangladesh Neonatal Hospital, Signboard Mor, Narayanganj',
    'Bangladesh Specialized Hospital',
    'Bangladesh Spine & Orthopaedic General Hospital Ltd, Panthapath, Dhaka',
    'Bangabandhu Memorial Hospital (BBMH), Chittagong',
    'Basundhura Hospital (Pvt.) Ltd.',
    'BGB Hospital',
    'BRB Hospital- Panthapath Dhaka',
    'Cardio Care Specialized and General Hospital Ltd, Dhaka',
    'Care Hospital, Dhaka',
    'Care Zone Hospital, Dhaka',
    'Catharsis Medical Centre Limited, Gazipur',
    'Central Hospital, Dhaka',
    'Chander Hasi Hospital Limited, Habiganj, Sylhet',
    'Charkhai Multicare Hospital, Beanibazar, Sylhet',
    'Chittagong Diabetic General Hospital',
    'Chittagong Eye Infirmary and Training Hospital',
    'Chittagong Maa-O-Shishu Hospital, Chittagong',
    'Chittagong Medical College Hospital',
    'CMH (Combined Military Hospital)',
    'Comilla Medical College Hospital, Comilla',
    'Continental Hospital Ltd.',
    'Cox\'s Bazar Hospital for Women & Children, Chittagong',
    'Dhaka Central International Medical College Hospital, Adabor, Dhaka',
    'Dhaka Community Hospital',
    'Dhaka Dental College and Hospital',
    'Dhaka Hospital, Dhaka',
    'Dhaka Medical College & Hospital',
    'Dhaka National Medical College And Hospital Institute',
    'Dhaka Shishu Hospital',
    'Dinajpur Medical College Hospital',
    'Dr. Alauddin Ahmed Clinic, Jhalakati',
    'Duwell Medical',
    'Eastern Hospital & Medical Research Centre',
    'Esperto Health Care & Research Center, Dhaka',
    'Evercare Hospital Dhaka',
    'Farazy Dental Hospital & Research Center, Dhaka',
    'Farazy Hospital Ltd, Dhaka',
    'Gazi Medical College Hospital, Khulna',
    'Genuine Cancer Hospital Limited, Chittagong',
    'Gonoshasthaya Nagar Hospital',
    'Government Employee Hospital',
    'Government Homeopathic Medical College Hospital',
    'Greenland Hospital Limited, Sector - 10, Uttara, Dhaka',
    'Holy Family Red Crescent Medical College Hospital, Dhaka',
    'Ibn Sina Hospital Sylhet Ltd',
    'Ibn Sina Hospitals, Dhaka',
    'Insaf Barakah Kidney and General Hospital',
    'Institute of Child and Mother Health, Dhaka',
    'Institute of Laser Surgery & Hospital, Dhaka',
    'Ispahani Islamia Eye Institute and Hospital (IIEI&H)',
    'Japan East West Medical College Hospital, Dhaka',
    'Khulna Medical College Hospital, Khulna',
    'Khwaja Yunus Ali Medical College and Hospital',
    'Kumudini Hospital, Tangail',
    'Kuwait Bangladesh Friendship Govt. Hospital, Uttara, Dhaka',
    'Labaid Cardiac Hospital, Dhaka',
    'Labaid Specialised Hospital, Dhaka',
    'Maa Nursing Home & Diagnostic Centre, Tangail',
    'M.A.G Osmani Medical College and Hospital, Sylhet',
    'Medinova Medical Services Ltd.',
    'Mental Hospital, Pabna',
    'MH Samorita Hospital & Medical College, love Road, Tejgaon, Dhaka',
    'Mikrani Dental Banasree Dhaka (Dental Hospital) Dhaka',
    'Mojibunnessa Eye Hospital, Dhaka',
    'Moulana Bhasani Medical College Hospital, Dhaka',
    'Mount Adora Hospital, Sylhet',
    'Mugda Medical College & Hospital, Dhaka',
    'Mymensingh Medical College Hospital',
    'National Heart Foundation, Sylhet',
    'National Hospital Chattagram, Chattagram',
    'National Institute of Cardiovascular Diseases',
    'National Institute of Ear, Nose and Throat',
    'National Institute of Kidney Disease & Urology',
    'National Institute of Mental Health',
    'National Institute of Mental Health and Hospital',
    'National Institute of Neuroscience',
    'National Institute of Opthalmology and Hospital',
    'National Institute of Preventive and Social Medicine',
    'North East Medical College and Hospital',
    'Nurjahan Hospital Ltd, Sylhet',
    'Oasis Hospital (Pvt) Ltd, Sylhet',
    'Pongu Hospital Jessore (Railget, Mujib Sarak, Jessore, Bangladesh)',
    'Popular Specialized Hospital Ltd.',
    'Rajshahi Medical College Hospital',
    'Rangpur Medical College Hospital, Rangpur',
    'Rashmono General Hospital, Dhaka',
    'Royal Hospital and research Center Ltd., Chittagong',
    'Saint Martin Hospital',
    'Samorita Hospital Ltd.',
    'Saphena Women\'s Dental College & Hospital',
    'Shaheed Ahsan Ullah Master General Hospital',
    'Shaheed Monsur Ali Medical College Hospital, Dhaka',
    'Shaheed Suhrawardy Medical College & Hospital',
    'Shaheed Ziaur Rahman Medical College Hospital, Bogra',
    'Shalahuddin Hospital',
    'Sheikh Fazilatunnessa Mujib Memorial KPJ Specialized Hospital & Nursing College',
    'Sher-e-Bangla Medical College Hospital, Barisal',
    'Siddiqia Eye Foundation, Mymensingh',
    'Sir Salimullah Medical College & Mitford Hospital, Dhaka',
    'Square Hospital Ltd., Dhaka',
    'Sylhet Eye Hospital & Laser Centre',
    'Sylhet Maa O Shishu Hospital',
    'Sylhet Medical College Hospital',
    'Sylhet Women\'s Medical College',
    'The Medical College for Women and Hospital',
    'Union Specialized Hospital Limited, Aftabnagor, Dhaka',
    'United Hospital Limited',
    'Z.H. Sikder Women\'s Medical College and Hospital (Pvt.) Ltd.',
  ];

  /// Get hospital name by index (for compatibility)
  static String? getHospitalByIndex(int index) {
    if (index >= 0 && index < bangladeshHospitals.length) {
      return bangladeshHospitals[index];
    }
    return null;
  }

  /// Find hospital index by name (for compatibility with existing data)
  static int? getHospitalIndex(String hospitalName) {
    final index = bangladeshHospitals.indexOf(hospitalName);
    return index >= 0 ? index : null;
  }

  /// Search hospitals by partial name match
  static List<String> searchHospitals(String query) {
    if (query.isEmpty) return bangladeshHospitals;

    final lowerQuery = query.toLowerCase();
    return bangladeshHospitals
        .where((hospital) => hospital.toLowerCase().contains(lowerQuery))
        .toList();
  }
}
