// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase project configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIYoEnv_MO6v6tcETFySQF5_jb8kWo-y4',
    appId: '1:638330305231:web:d60d4fbd8ececa7a5255ba',
    messagingSenderId: '638330305231',
    projectId: 'doclinker-991da',
    authDomain: 'doclinker-991da.firebaseapp.com',
    storageBucket: 'doclinker-991da.firebasestorage.app',
    measurementId: 'G-5K6R0KRN6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5ABKPo6hnLRbity51csAprnIz6BxnTk',
    appId: '1:638330305231:android:7f81e40eee9ac5775255ba',
    messagingSenderId: '638330305231',
    projectId: 'doclinker-991da',
    storageBucket: 'doclinker-991da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmxu05GYPQBjE_zU6nZZsJoqMLKkqs0Q',
    appId: '1:638330305231:ios:859e3b3ec84f4f485255ba',
    messagingSenderId: '638330305231',
    projectId: 'doclinker-991da',
    storageBucket: 'doclinker-991da.firebasestorage.app',
    androidClientId:
        '638330305231-6af55pg9j89d1pcg0hco7ha3o5qf3f5k.apps.googleusercontent.com',
    iosClientId:
        '638330305231-tfpn5p4aj250vdii06u8j06uslifiptk.apps.googleusercontent.com',
    iosBundleId: 'com.example.doclinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: '123456789',
    projectId: 'doclinker-dev',
    storageBucket: 'doclinker-dev.appspot.com',
    iosClientId: 'mock-ios-client-id',
    iosBundleId: 'com.example.doclinker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: '123456789',
    projectId: 'doclinker-dev',
    storageBucket: 'doclinker-dev.appspot.com',
  );
}
